In [1]:
import pandas as pd

## FORNECEDOR

In [19]:
df_fornecedor = pd.read_excel('../raw/fornecedor.xlsx')
df_fornecedor['COD_FORNECEDOR'] = df_fornecedor['COD_FORNECEDOR'].apply(lambda x: str(x).zfill(2)).astype('str')
df_fornecedor

  COD_FORNECEDOR    FORNECEDOR
0             01  CAMILA CALSA
1             02   RE CASCIANO
2             03       DAVENZO
3             06         ROSAH
4             07           PPL

## PRODUTOS

In [21]:
df_novos_produtos = pd.read_excel('../raw/2- PRODUTOS - PRECIFICAÇAO segunda compra 09.02.xlsx', sheet_name='Sheet1', skiprows=1)
df_novos_produtos

,CONCATENAR,METAL,FOTO,SKU,DESCRICAO,CODIGO FORNECEDOR,GRUPO,LINHA,QUANT,PESO(g),...,TAXA_CREDITO,MARGEM,Coluna1,VALOR_VENDA,VALOR FINAL,VALOR FINAL AJUSTADO,VALOR COM COM,com revenda,sem revenda,status
0,ANELDIA A DIA,AG,NaN,NaN,ANEL 2 PALITOS ARO REGULAVEL ate 23,AN059,ANEL,DIA A DIA,5.0,1.00,...,5.509427,22.037709,28.696814,28.696814,29.9,39.9,23.94,3.718973,4.718973,NaN
1,ANELDIA A DIA,AU,NaN,NaN,ANEL 2 PALITOS ARO REGULAVEL ate 23,AN059,ANEL,DIA A DIA,5.0,1.00,...,13.387718,53.550874,60.209979,60.209979,65.9,59.9,35.94,1.915421,2.915421,NaN
2,ANELDIA A DIA,AG,NaN,NaN,"ANEL FIO 1,2MM ONDA TAM 17",AN146,ANEL,DIA A DIA,3.0,0.60,...,7.084936,28.339745,34.998850,34.998850,35.9,35.9,21.54,2.301715,3.301715,NaN
3,ANELDIA A DIA,AU,NaN,NaN,"ANEL FIO 1,2MM ONDA tam 19",AN146,ANEL,DIA A DIA,3.0,0.60,...,11.811911,47.247644,53.906749,53.906749,55.9,55.9,33.54,2.083704,3.083704,NaN
4,ANELDIA A DIA,AG,NaN,NaN,ANEL REGULAVEL 2 CORACOES TAM 18,AN150,ANEL,DIA A DIA,3.0,1.20,...,10.694673,42.778691,49.437796,49.437796,49.9,35.9,21.54,1.187298,2.187298,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,BRINCODIA A DIA,AU,NaN,NaN,TRIO REDONDO ZIRC GALERIA,BR9961,BRINCO,DIA A DIA,2.0,3.80,...,47.274761,189.099042,196.830647,196.830647,195.9,129.9,77.94,0.790445,1.790445,NaN
90,BRINCODIA A DIA,AG,NaN,NaN,TRIO REDONDO ZIRC GALERIA,BR9961,BRINCO,DIA A DIA,1.0,3.80,...,24.237264,96.949054,104.680659,104.680659,105.9,109.9,65.94,1.954576,2.954576,NaN
91,BRINCODIA A DIA,AG,NaN,NaN,TRIO TREVO DIVERSOS,TRB0125,BRINCO,DIA A DIA,3.0,3.12,...,27.024229,108.096916,115.828521,115.828521,115.9,129.9,77.94,2.132109,3.132109,NaN
92,BRINCODIA A DIA,AU,NaN,NaN,TRIO TREVO DIVERSOS,TRB0125,BRINCO,DIA A DIA,2.0,3.12,...,45.939227,183.756906,191.488511,191.488511,195.9,159.9,95.94,1.268015,2.268015,NaN
93,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.000000,NaN

In [22]:
df_novos_produtos.columns

Index(['CONCATENAR', 'METAL', 'FOTO', 'SKU', 'DESCRICAO', 'CODIGO FORNECEDOR',
       'GRUPO', 'LINHA', 'QUANT', 'PESO(g)', 'FORNECEDOR', 'VALOR_UNIT',
       'TOTAL PESO', 'VARIAÇAO PESO GALV', 'FRETE POR PEÇA', 'CAMADA',
       'VERNIZ + PALADIO', 'GALVANIZAÇAO', 'SERVICO',
       'DESEMBOLSO TOTAL - VALOR UNITARIO', 'BOLSA + PAPELARIAS PADRAO', 'TAG',
       'ETIQUETA', 'VALOR SEM TAXAS', 'TAXA_CREDITO', 'MARGEM', 'Coluna1',
       'VALOR_VENDA', 'VALOR FINAL', 'VALOR FINAL AJUSTADO', 'VALOR COM COM',
       'com revenda', 'sem revenda', 'status'],
      dtype='object')

In [39]:
df_novos_produtos['COD_FORNECEDOR'] = df_novos_produtos['FORNECEDOR'].astype(str).str[-2:]

In [44]:
df_novos_produtos['INDEX'] = df_novos_produtos['INDEX'] = range(148, 148 + len(df_novos_produtos))
df_novos_produtos['INDEX'] = df_novos_produtos['INDEX'].apply(lambda x: str(x).zfill(6))
df_novos_produtos['SKU'] = df_novos_produtos['COD_FORNECEDOR'].astype(str) + df_novos_produtos['INDEX'].astype(str) + df_novos_produtos['METAL']
df_novos_produtos_sku = df_novos_produtos[['DESCRICAO', 'SKU']]
# df_novos_produtos_sku.loc[df_novos_produtos_sku['SKU'].isna()]
df_novos_produtos_sku.drop(index=93, inplace=True)

/tmp/ipykernel_73714/2177883721.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_novos_produtos_sku.drop(index=93, inplace=True)

In [47]:
df_novos_produtos_sku.to_csv('../output/produtos_sku.csv', index=False, encoding='latin-1')